menu:
  home: Home
  archive: Archive
  rss: RSS
  tags: Tags
index:
  read_more: Read full article
  categories: Categories
  tags: Tags
sitemap:
  title: Sitemap
  archives: Archives
  categories: Categories
  tags: Tags
